### ISSUE TITLE
changing camera

### ISSUE THREAD

**Issue by kazem3d** [ysuzuki19/react-qrcode-reader#1]
how can change camera?

**Comment by ysuzuki19** [comment]
Thank you for asking question.

Now, its not supported.

By my search, we might to solve it with `videoConstraints` prop of `<WebCam>`.
Its documented [here](https://github.com/mozmorris/react-webcam#props).

Do you fix it yourself?
If not, I will try when I have time. :)

**Comment by kazem3d** [comment]
Hi
I solved the problem with
adding videoConstrains prob to your code
But i suggest you to add videoConstrains to your code and also turn on
flashlight

**Comment by ysuzuki19** [comment]
@kazem3d 

Thank you for the idea!

Result of my consideration, I adopt `deviceId` prop for the component as optional (since v1.1.0).

But I didn't implemented flashlight (or torch) because I cannot test it.

**Comment by kazem3d** [comment]
Thanks a lot

**Comment by ysuzuki19** [comment]
The interface of this feature is changed by #6 .

For migration, please read the [doc](https://github.com/ysuzuki19/react-qrcode-reader/blob/main/MIGRATION.md#1-to-2)
