### ISSUE TITLE
Rear-facing Camera compatibility

### ISSUE THREAD

**Issue by JamirGVTimes** [ysuzuki19/react-qrcode-reader#12]
Good app so far, however, I'm missing the rear-facing camera for the case of Mobile Devices. 
It only has the front-camera mode.
Kindly check it out

**Comment by ysuzuki19** [comment]
This library delegates the operation of the webcam to `react-webcam` by the prop `videoConstraints`. 

https://github.com/ysuzuki19/react-qrcode-reader/blob/d7903dc0d986d1e304aa5874a0a26846290a48ed/package/lib/index.tsx#L59

Therefore, the approach to rear-facing should be achievable using a method equivalent to that in `react-webcam`.

Please search the method.

If you want to add pass other props, just let me know :)

**Comment by JamirGVTimes** [comment]
Kindly add pass other props so that it's achievable

**Comment by ysuzuki19** [comment]
Could you tell me the prop name of `react-webcam` for your achieve the purpose

**Comment by JamirGVTimes** [comment]
Instead of using facingMode:"user"
I wish to use facingMode: { exact: "environment" }
like below 
class WebcamCapture extends React.Component {
  render() {
    const videoConstraints = {
      facingMode: { exact: "environment" }
    };

    return <Webcam videoConstraints={videoConstraints} />;
  }
}

you can give it any prop name.

Thank you

**Comment by ysuzuki19** [comment]
Can resolve the purpose with below code?

```ts
<QrCodeReader
  delay={100}
  width={500}
  height={500}
  onRead={handleRead}
  videoConstraints={{
    facingMode: { exact: "environment" }
  }}
/>
```

**Comment by JamirGVTimes** [comment]
Thanks very much, it's working perfectly.
A lot of libraries have failed, but this has succeded to me.
