### ISSUE TITLE
Choose camera option

### ISSUE THREAD

**Issue by DevNadine** [ysuzuki19/react-qrcode-reader#5]
It keeps opening the front camera on my mobile device. Wouldn't it be more practical if the user could pass the complete videoConstraints instead of just the deviceId? That way, users could specify the 'facing'-value as well as any other required value. Or you could add a facing-Prop and change line 59 to "videoConstraints={{ deviceId: deviceId, facingMode: facing || 'environment' }}"

**Comment by agustencp** [comment]
Hey @ysuzuki19, is it possible to add `facingMode` parameter, like the `deviceId` on `QrCodeReader`?
Thank you!

**Comment by agustencp** [comment]
By the way, I just created a pull request with the change: https://github.com/ysuzuki19/react-qrcode-reader/pull/6

**Comment by DevNadine** [comment]
Thx
